# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gets the Standard Error from a coefficient variance matrix
#'
#' @param x Numeric vector in R
#'
#' @param n integer in R
#'
StandardError <- function(x, n) {
    .Call(`_HW3project_StandardError`, x, n)
}

